### ISSUE TITLE
Group messaging not working – Always returns "No sessions" while session is active

### ISSUE THREAD

**Issue by azeezeladl** [Itsukichann/Baileys#11]
When I send an image message to a group using WhiskeySockets/Baileys, everything works perfectly. Here's a successful response example:

{
  "status": "success",
  "message": {
    "key": {
      "remoteJid": "120363400175739990@g.us",
      "fromMe": true,
      "id": "3EB0CB1CBCF248BA83A2DD"
    },
    "message": {
      "imageMessage": {
        "url": "https://mmg.whatsapp.net/...",
        "caption": "test message",
        "mimetype": "image/jpeg"
        // ... more metadata
      }
    },
    "messageTimestamp": "1751688579",
    "status": "SUCCESS",
    "participant": "201011227811:23@s.whatsapp.net"
  }
}

❌ What fails with Itsukichann/Baileys:
Using the exact same code and message structure, I get this response instead:

{
  "status": "success",
  "message": "No sessions"
}

Even though:

💡 Expected:
Group messages (image, text, etc.) should send normally if session is valid and groupMetadata is accessible.

📌 Notes:
Everything works for individual chats (@c.us).

Group messaging used to work before migrating.

I'm using await sock.sendMessage(groupJid, message) as usual.

Thanks for your time and for maintaining this great fork 🙏! Let me know if I should provide reproduction code.

**Comment by azeezeladl** [comment]
This message is showing now.

{"status":"success","message":"not-acceptable"}

**Comment by Itsukichann** [comment]
> When I send an image message to a group using WhiskeySockets/Baileys, everything works perfectly. Here's a successful response example:
> 
> {
>   "status": "success",
>   "message": {
>     "key": {
>       "remoteJid": "120363400175739990@g.us",
>       "fromMe": true,
>       "id": "3EB0CB1CBCF248BA83A2DD"
>     },
>     "message": {
>       "imageMessage": {
>         "url": "https://mmg.whatsapp.net/...",
>         "caption": "test message",
>         "mimetype": "image/jpeg"
>         // ... more metadata
>       }
>     },
>     "messageTimestamp": "1751688579",
>     "status": "SUCCESS",
>     "participant": "201011227811:23@s.whatsapp.net"
>   }
> }
> 
> ❌ What fails with Itsukichann/Baileys:
> Using the exact same code and message structure, I get this response instead:
> 
> {
>   "status": "success",
>   "message": "No sessions"
> }
> 
> Even though:
> 
> 💡 Expected:
> Group messages (image, text, etc.) should send normally if session is valid and groupMetadata is accessible.
> 
> 📌 Notes:
> Everything works for individual chats (@c.us).
> 
> Group messaging used to work before migrating.
> 
> I'm using await sock.sendMessage(groupJid, message) as usual.
> 
> Thanks for your time and for maintaining this great fork 🙏! Let me know if I should provide reproduction code.
> 
> 

Thank you for the notification, I will try the repair.

**Comment by azeezeladl** [comment]
> > When I send an image message to a group using WhiskeySockets/Baileys, everything works perfectly. Here's a successful response example:
> > {
> > "status": "success",
> > "message": {
> > "key": {
> > "remoteJid": "[120363400175739990@g.us](mailto:120363400175739990@g.us)",
> > "fromMe": true,
> > "id": "3EB0CB1CBCF248BA83A2DD"
> > },
> > "message": {
> > "imageMessage": {
> > "url": "https://mmg.whatsapp.net/...",
> > "caption": "test message",
> > "mimetype": "image/jpeg"
> > // ... more metadata
> > }
> > },
> > "messageTimestamp": "1751688579",
> > "status": "SUCCESS",
> > "participant": "201011227811:[23@s.whatsapp.net](mailto:23@s.whatsapp.net)"
> > }
> > }
> > ❌ What fails with Itsukichann/Baileys:
> > Using the exact same code and message structure, I get this response instead:
> > {
> > "status": "success",
> > "message": "No sessions"
> > }
> > Even though:
> > 💡 Expected:
> > Group messages (image, text, etc.) should send normally if session is valid and groupMetadata is accessible.
> > 📌 Notes:
> > Everything works for individual chats (@c.us).
> > Group messaging used to work before migrating.
> > I'm using await sock.sendMessage(groupJid, message) as usual.
> > Thanks for your time and for maintaining this great fork 🙏! Let me know if I should provide reproduction code.
> 
> Thank you for the notification, I will try the repair.

This issue was also present in the main library and has been resolved in the latest versions. Thank you for your interest and quick response. I await your update.

**Comment by Itsukichann** [comment]
> > > When I send an image message to a group using WhiskeySockets/Baileys, everything works perfectly. Here's a successful response example:
> > > {
> > > "status": "success",
> > > "message": {
> > > "key": {
> > > "remoteJid": "[120363400175739990@g.us](mailto:120363400175739990@g.us)",
> > > "fromMe": true,
> > > "id": "3EB0CB1CBCF248BA83A2DD"
> > > },
> > > "message": {
> > > "imageMessage": {
> > > "url": "https://mmg.whatsapp.net/...",
> > > "caption": "test message",
> > > "mimetype": "image/jpeg"
> > > // ... more metadata
> > > }
> > > },
> > > "messageTimestamp": "1751688579",
> > > "status": "SUCCESS",
> > > "participant": "201011227811:[23@s.whatsapp.net](mailto:23@s.whatsapp.net)"
> > > }
> > > }
> > > ❌ What fails with Itsukichann/Baileys:
> > > Using the exact same code and message structure, I get this response instead:
> > > {
> > > "status": "success",
> > > "message": "No sessions"
> > > }
> > > Even though:
> > > 💡 Expected:
> > > Group messages (image, text, etc.) should send normally if session is valid and groupMetadata is accessible.
> > > 📌 Notes:
> > > Everything works for individual chats (@c.us).
> > > Group messaging used to work before migrating.
> > > I'm using await sock.sendMessage(groupJid, message) as usual.
> > > Thanks for your time and for maintaining this great fork 🙏! Let me know if I should provide reproduction code.
> > 
> > Thank you for the notification, I will try the repair.
> 
> This issue was also present in the main library and has been resolved in the latest versions. Thank you for your interest and quick response. I await your update.

Hi, thanks for waiting! I've just pushed an update to my repository. Could you try reinstalling the GitHub version and let me know if it works better or if the issue persists? Thanks!

**Comment by azeezeladl** [comment]
> > > > When I send an image message to a group using WhiskeySockets/Baileys, everything works perfectly. Here's a successful response example:
> > > > {
> > > > "status": "success",
> > > > "message": {
> > > > "key": {
> > > > "remoteJid": "[120363400175739990@g.us](mailto:120363400175739990@g.us)",
> > > > "fromMe": true,
> > > > "id": "3EB0CB1CBCF248BA83A2DD"
> > > > },
> > > > "message": {
> > > > "imageMessage": {
> > > > "url": "https://mmg.whatsapp.net/...",
> > > > "caption": "test message",
> > > > "mimetype": "image/jpeg"
> > > > // ... more metadata
> > > > }
> > > > },
> > > > "messageTimestamp": "1751688579",
> > > > "status": "SUCCESS",
> > > > "participant": "201011227811:[23@s.whatsapp.net](mailto:23@s.whatsapp.net)"
> > > > }
> > > > }
> > > > ❌ What fails with Itsukichann/Baileys:
> > > > Using the exact same code and message structure, I get this response instead:
> > > > {
> > > > "status": "success",
> > > > "message": "No sessions"
> > > > }
> > > > Even though:
> > > > 💡 Expected:
> > > > Group messages (image, text, etc.) should send normally if session is valid and groupMetadata is accessible.
> > > > 📌 Notes:
> > > > Everything works for individual chats (@c.us).
> > > > Group messaging used to work before migrating.
> > > > I'm using await sock.sendMessage(groupJid, message) as usual.
> > > > Thanks for your time and for maintaining this great fork 🙏! Let me know if I should provide reproduction code.
> > > 
> > > 
> > > Thank you for the notification, I will try the repair.
> > 
> > 
> > This issue was also present in the main library and has been resolved in the latest versions. Thank you for your interest and quick response. I await your update.
> 
> Hi, thanks for waiting! I've just pushed an update to my repository. Could you try reinstalling the GitHub version and let me know if it works better or if the issue persists? Thanks!

أHi,

The problem hasn't been resolved. I think this might be helpful.

https://github.com/WhiskeySockets/Baileys/commit/a4338fac12a54a36890845c99abd56e92b88cdf6

https://github.com/WhiskeySockets/Baileys/commit/99bbafeae51d660534450ff30b223548171ba273

https://github.com/WhiskeySockets/Baileys/commit/53d6e3a8d5d8b141b2c806a09ba59ae50957f6f5

**Comment by azeezeladl** [comment]
> > > > > > When I send an image message to a group using WhiskeySockets/Baileys, everything works perfectly. Here's a successful response example:
> > > > > > {
> > > > > > "status": "success",
> > > > > > "message": {
> > > > > > "key": {
> > > > > > "remoteJid": "[120363400175739990@g.us](mailto:120363400175739990@g.us)",
> > > > > > "fromMe": true,
> > > > > > "id": "3EB0CB1CBCF248BA83A2DD"
> > > > > > },
> > > > > > "message": {
> > > > > > "imageMessage": {
> > > > > > "url": "https://mmg.whatsapp.net/...",
> > > > > > "caption": "test message",
> > > > > > "mimetype": "image/jpeg"
> > > > > > // ... more metadata
> > > > > > }
> > > > > > },
> > > > > > "messageTimestamp": "1751688579",
> > > > > > "status": "SUCCESS",
> > > > > > "participant": "201011227811:[23@s.whatsapp.net](mailto:23@s.whatsapp.net)"
> > > > > > }
> > > > > > }
> > > > > > ❌ What fails with Itsukichann/Baileys:
> > > > > > Using the exact same code and message structure, I get this response instead:
> > > > > > {
> > > > > > "status": "success",
> > > > > > "message": "No sessions"
> > > > > > }
> > > > > > Even though:
> > > > > > 💡 Expected:
> > > > > > Group messages (image, text, etc.) should send normally if session is valid and groupMetadata is accessible.
> > > > > > 📌 Notes:
> > > > > > Everything works for individual chats (@c.us).
> > > > > > Group messaging used to work before migrating.
> > > > > > I'm using await sock.sendMessage(groupJid, message) as usual.
> > > > > > Thanks for your time and for maintaining this great fork 🙏! Let me know if I should provide reproduction code.
> > > > > 
> > > > > 
> > > > > Thank you for the notification, I will try the repair.
> > > > 
> > > > 
> > > > This issue was also present in the main library and has been resolved in the latest versions. Thank you for your interest and quick response. I await your update.
> > > 
> > > 
> > > Hi, thanks for waiting! I've just pushed an update to my repository. Could you try reinstalling the GitHub version and let me know if it works better or if the issue persists? Thanks!
> > 
> > 
> > أHi,
> > The problem hasn't been resolved. I think this might be helpful.
> > [WhiskeySockets/Baileys@a4338fa](https://github.com/WhiskeySockets/Baileys/commit/a4338fac12a54a36890845c99abd56e92b88cdf6)
> > [WhiskeySockets/Baileys@99bbafe](https://github.com/WhiskeySockets/Baileys/commit/99bbafeae51d660534450ff30b223548171ba273)
> > [WhiskeySockets/Baileys@53d6e3a](https://github.com/WhiskeySockets/Baileys/commit/53d6e3a8d5d8b141b2c806a09ba59ae50957f6f5)
> 
> I have completed all the necessary steps. Could you kindly provide the group link so that I may proceed with testing it directly?

https://waclient.com/api/send_group?group_id=120363400175739990@g.us&type=text&message=test+message&instance_id=67C179BD3D166&access_token=EMCUH3NQQK8YG7BY

**Comment by Itsukichann** [comment]
> > > > > > > When I send an image message to a group using WhiskeySockets/Baileys, everything works perfectly. Here's a successful response example:
> > > > > > > {
> > > > > > > "status": "success",
> > > > > > > "message": {
> > > > > > > "key": {
> > > > > > > "remoteJid": "[120363400175739990@g.us](mailto:120363400175739990@g.us)",
> > > > > > > "fromMe": true,
> > > > > > > "id": "3EB0CB1CBCF248BA83A2DD"
> > > > > > > },
> > > > > > > "message": {
> > > > > > > "imageMessage": {
> > > > > > > "url": "https://mmg.whatsapp.net/...",
> > > > > > > "caption": "test message",
> > > > > > > "mimetype": "image/jpeg"
> > > > > > > // ... more metadata
> > > > > > > }
> > > > > > > },
> > > > > > > "messageTimestamp": "1751688579",
> > > > > > > "status": "SUCCESS",
> > > > > > > "participant": "201011227811:[23@s.whatsapp.net](mailto:23@s.whatsapp.net)"
> > > > > > > }
> > > > > > > }
> > > > > > > ❌ What fails with Itsukichann/Baileys:
> > > > > > > Using the exact same code and message structure, I get this response instead:
> > > > > > > {
> > > > > > > "status": "success",
> > > > > > > "message": "No sessions"
> > > > > > > }
> > > > > > > Even though:
> > > > > > > 💡 Expected:
> > > > > > > Group messages (image, text, etc.) should send normally if session is valid and groupMetadata is accessible.
> > > > > > > 📌 Notes:
> > > > > > > Everything works for individual chats (@c.us).
> > > > > > > Group messaging used to work before migrating.
> > > > > > > I'm using await sock.sendMessage(groupJid, message) as usual.
> > > > > > > Thanks for your time and for maintaining this great fork 🙏! Let me know if I should provide reproduction code.
> > > > > > 
> > > > > > 
> > > > > > Thank you for the notification, I will try the repair.
> > > > > 
> > > > > 
> > > > > This issue was also present in the main library and has been resolved in the latest versions. Thank you for your interest and quick response. I await your update.
> > > > 
> > > > 
> > > > Hi, thanks for waiting! I've just pushed an update to my repository. Could you try reinstalling the GitHub version and let me know if it works better or if the issue persists? Thanks!
> > > 
> > > 
> > > أHi,
> > > The problem hasn't been resolved. I think this might be helpful.
> > > [WhiskeySockets/Baileys@a4338fa](https://github.com/WhiskeySockets/Baileys/commit/a4338fac12a54a36890845c99abd56e92b88cdf6)
> > > [WhiskeySockets/Baileys@99bbafe](https://github.com/WhiskeySockets/Baileys/commit/99bbafeae51d660534450ff30b223548171ba273)
> > > [WhiskeySockets/Baileys@53d6e3a](https://github.com/WhiskeySockets/Baileys/commit/53d6e3a8d5d8b141b2c806a09ba59ae50957f6f5)
> > 
> > I have completed all the necessary steps. Could you kindly provide the group link so that I may proceed with testing it directly?
> 
> https://waclient.com/api/send_group?group_id=120363400175739990@g.us&type=text&message=test+message&instance_id=67C179BD3D166&access_token=EMCUH3NQQK8YG7BY

I am referring to a link similar to this: https://chat.whatsapp.com/....

**Comment by vy-yos** [comment]
El mismo error aqui

**Comment by azeezeladl** [comment]
> El mismo error aqui

I used version 7.3.0 and the problem was solved for me

**Comment by Itsukichann** [comment]
> > El mismo error aqui
> 
> I used version 7.3.0 and the problem was solved for me

Hello, could you please test my latest repository? I believe the issue has been resolved, and I look forward to receiving your feedback. Thank you.

**Comment by Dioneibi-rip** [comment]
> > > El mismo error aquí
> > 
> > 
> > Utilicé la versión 7.3.0 y el problema se solucionó para mí.
> 
> Hola, ¿podrías probar mi último repositorio? Creo que el problema se ha resuelto y espero tus comentarios. Gracias.

It wasn't fixed, I'm still getting this error and I don't know how to fix it 😞 SessionError: No sessions at 12048160103.10 [as awaitable] (/home/container/node_modules/@itsukichan/libsignal-node/src/session_cipher.js:71:23) at async _asyncQueueExecutor (/home/container/node_modules/@itsukichan/libsignal-node/src/queue_job.js:20:29)

**Comment by azeezeladl** [comment]
> > > El mismo error aqui
> > 
> > 
> > I used version 7.3.0 and the problem was solved for me
> 
> Hello, could you please test my latest repository? I believe the issue has been resolved, and I look forward to receiving your feedback. Thank you.

Hi Itsukichann,

I did what you asked, but the problem still exists. The latest update shows an error message: "No sessions."
The version that works well for me now is:

npm:@itsukichan/baileys@7.3.0

**Comment by bxssdxrk** [comment]
> 
> Hi Itsukichann,
> 
> I did what you asked, but the problem still exists. The latest update shows an error message: "No sessions." The version that works well for me now is:
> 
> npm:@itsukichan/baileys@7.3.0

Have you tried deleting the authentication files and pairing again?
